apiVersion: v1
kind: Service
metadata:
  name: devops-lab-dev-service
  namespace: jenkins
spec:
  selector:
    app: devops-lab-dev
  ports:
    - protocol: TCP
      port: 3000       # Puerto en el que el servicio escucha dentro del clúster
      targetPort: 3000 # Puerto en el que el contenedor escucha
      nodePort: 32001  # Puerto en el nodo que expone el servicio
  type: NodePort
